#lang racket
(define (listen-verschmelzen eingabe)
  (define (merge eingabe newList)
    (if (null? eingabe)
        (append newList eingabe)
        (if (list? eingabe)
            (merge (cdr eingabe) (append newList (car eingabe)))
            (merge (cdr eingabe) (append newList eingabe))
            )
        )
    )
  (merge eingabe '())
  )

(listen-verschmelzen '((1 3 5 7 9) (2 4 6 8)))
(listen-verschmelzen '((1 3 5 7 9) (2 4 6 8 10)))
(listen-verschmelzen '(() ()))