#lang racket
(define (liste-teilen eingabe)
  (define (devide eingabe newList  newList2 counter)
    (if (null? eingabe)
       (list newList newList2)
       (if (odd? counter)
           (devide (cdr eingabe) (append newList (list (car eingabe))) newList2 (+ counter 1))
           (devide (cdr eingabe) newList (append newList2 (list (car eingabe))) (+ counter 1))
           )
       )
    )
  (devide eingabe '() '() 1)
  ) 

(liste-teilen '(1 2 3 4 5 6 7 8 9))
(liste-teilen '(1 2 3 4 5 6 7 8 9 10))
(liste-teilen '())